# Financement et Sponsoring - OPTIRH

# GitHub Sponsors
# github: [dreykovic]

# Open Collective
# open_collective: optirh

# Patreon
# patreon: optirh

# Ko-fi
# ko_fi: optirh

# Liberapay
# liberapay: optirh

# PayPal
# paypal: dreykovic

# Custom funding URLs
custom: 
  - "https://optirh.votre-domaine.com/sponsor"
  - "mailto:sponsor@optirh.com"