name: 🐛 Rapport de Bug
description: Signaler un problème ou dysfonctionnement dans OPTIRH
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - Dreykovic

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug. Plus les informations sont détaillées, plus vite nous pourrons le résoudre !

  - type: checkboxes
    id: checks
    attributes:
      label: Vérifications préalables
      description: Veuillez confirmer les points suivants
      options:
        - label: J'ai vérifié qu'il n'existe pas déjà un issue similaire
          required: true
        - label: J'utilise la dernière version disponible
          required: true
        - label: J'ai consulté la documentation
          required: true

  - type: dropdown
    id: module
    attributes:
      label: Module concerné
      description: Dans quel module le bug apparaît-il ?
      options:
        - OptiHR - Gestion du personnel
        - OptiHR - Gestion des absences
        - OptiHR - Demandes de documents
        - OptiHR - Publications
        - OptiHR - Tableaux de bord
        - Recours - Soumission de recours
        - Recours - Traitement des recours
        - Authentification/Connexion
        - API REST
        - Interface générale
        - Configuration/Installation
        - Autre
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Gravité du bug
      description: Quel est l'impact du problème ?
      options:
        - Critique - L'application ne fonctionne plus
        - Élevée - Fonctionnalité principale cassée
        - Moyenne - Fonctionnalité secondaire affectée
        - Faible - Problème mineur ou cosmétique
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré
      placeholder: |
        Exemple : Lorsque je clique sur "Valider" dans la page des absences, j'obtiens une erreur 500 et la demande n'est pas enregistrée.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment peut-on reproduire ce bug ?
      placeholder: |
        1. Aller sur la page '...'
        2. Cliquer sur '...'
        3. Remplir le champ '...' avec '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: La demande d'absence devrait être enregistrée et une notification de confirmation apparaître.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement observé
      description: Que se passe-t-il réellement ?
      placeholder: Une page d'erreur 500 s'affiche avec le message "Internal Server Error"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      description: Sur quel environnement le bug apparaît-il ?
      options:
        - Production
        - Staging/Test
        - Développement local
        - Docker
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Détails techniques
      description: |
        Informations sur votre environnement :
        - Version d'OPTIRH
        - Version PHP
        - Version Laravel
        - Navigateur et version
        - Système d'exploitation
      placeholder: |
        - OPTIRH: v1.0.0
        - PHP: 8.1.2
        - Laravel: 10.x
        - Navigateur: Chrome 120.0.0
        - OS: Ubuntu 22.04

  - type: textarea
    id: logs
    attributes:
      label: Messages d'erreur et logs
      description: Copiez ici les messages d'erreur, logs Laravel, ou erreurs JavaScript
      placeholder: |
        [2024-01-15 10:30:00] local.ERROR: SQLSTATE[23000]: Integrity constraint violation...
        
        Erreur console JavaScript :
        Uncaught TypeError: Cannot read property 'value' of null...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran pour illustrer le problème
      placeholder: Glissez-déposez vos images ici ou utilisez le bouton "Attach files"

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Toute autre information utile (contournement temporaire, fréquence du problème, etc.)
      placeholder: |
        - Le bug n'apparaît qu'avec certains types d'utilisateurs
        - Contournement temporaire : utiliser l'API directement
        - Fréquence : 3 fois sur 10 tentatives