<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Browser Homepage Enhanced</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/my-task.style.min.css') }}">
    <!-- Font Awesome pour les icônes -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/css/gateway.css') }}">

</head>

<body>
    <div class="browser-container">
        <!-- Zone de contenu principale -->
        <div class="content-area h-100">
            <div class="search-container">
                <div class="logo text-center mb-4">
                    <img src="/api/placeholder/50/50" alt="Browser logo" class="rounded-circle bg-white p-2">
                </div>

                <div class="search-box">
                    <i class="fa-brands fa-google search-icon"></i>
                    <input type="text" placeholder="Search the web">
                    <i class="fas fa-search text-muted ms-2"></i>
                </div>

                <div class="shortcuts-container">
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon medium-icon">
                            <i class="fab fa-medium-m text-white"></i>
                        </div>
                        <div class="shortcut-name">Medium</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon twitch-icon">
                            <i class="fab fa-twitch text-white"></i>
                        </div>
                        <div class="shortcut-name">Twitch</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon reddit-icon">
                            <i class="fab fa-reddit-alien text-white"></i>
                        </div>
                        <div class="shortcut-name">Reddit</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon twitter-icon">
                            <i class="fab fa-twitter text-white"></i>
                        </div>
                        <div class="shortcut-name">Twitter</div>
                    </a>

                    <a href="#" class="shortcut">
                        <div class="shortcut-icon airbnb-icon">
                            <i class="fab fa-airbnb text-white"></i>
                        </div>
                        <div class="shortcut-name">Airbnb</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon youtube-icon">
                            <i class="fab fa-youtube text-white"></i>
                        </div>
                        <div class="shortcut-name">Youtube</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon netflix-icon">
                            <i class="fas fa-play text-white"></i>
                        </div>
                        <div class="shortcut-name">Netflix</div>
                    </a>
                    <a href="#" class="shortcut">
                        <div class="shortcut-icon">
                            <i class="fas fa-plus add-icon"></i>
                        </div>
                        <div class="shortcut-name">Add a site</div>
                    </a>
                </div>
            </div>

            <div class="dots-container">
                <!-- Generated by JS -->
            </div>
        </div>
    </div>

    <div class="footer">
        <p>© 2025 | Enhanced Browser Experience</p>
    </div>

    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

    <!-- Script for animated background dots -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const dotsContainer = document.querySelector('.dots-container');
            const dotCount = 30;

            for (let i = 0; i < dotCount; i++) {
                const dot = document.createElement('div');
                dot.classList.add('dot');

                // Random position
                const x = Math.random() * 100;
                const y = Math.random() * 100;

                dot.style.top = `${y}%`;
                dot.style.left = `${x}%`;
                dot.style.opacity = Math.random() * 0.5 + 0.1;
                dot.style.width = `${Math.random() * 5 + 3}px`;
                dot.style.height = dot.style.width;

                // Random animation
                const duration = Math.random() * 20 + 10;
                const delay = Math.random() * 5;

                dot.style.animation = `float ${duration}s ease-in-out ${delay}s infinite`;

                dotsContainer.appendChild(dot);
            }
        });

        // Animation for floating dots
        document.head.insertAdjacentHTML('beforeend', `
            <style>
                @keyframes float {
                    0%, 100% { transform: translateY(0) translateX(0); }
                    25% { transform: translateY(-20px) translateX(10px); }
                    50% { transform: translateY(-35px) translateX(-15px); }
                    75% { transform: translateY(-15px) translateX(15px); }
                }
            </style>
        `);
    </script>
</body>

</html>
